#DB
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 1234
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: user-service

#SV
SERVER_PORT: 9501
ACTIVE_PROFILE: test

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <EMAIL_ADDRESS>
EMAIL_PASSWORD: <APP_PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
